/** GET CATEGORY API */
export const GET_CATEGORY_PROGRESS = "GET_CATEGORY_PROGRESS";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

/** POST CATEGORY API */
export const POST_CATEGORY_PROGRESS = "POST_CATEGORY_PROGRESS";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_ERROR = "POST_CATEGORY_ERROR";
export const POST_CATEGORY_DUPLICATE = "POST_CATEGORY_DUPLICATE";

/** DELETE CATEGORY API */
export const DELETE_CATEGORY_PROGRESS = "DELETE_CATEGORY_PROGRESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

/** UPDATE CATEGORY API */
export const UPDATE_CATEGORY_PROGRESS = "UPDATE_CATEGORY_PROGRESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
