/** GET childSubCategory API */
export const GET_CHILD_SUB_CATEGORY_PROGRESS =
  "GET_CHILD_SUB_CATEGORY_PROGRESS";
export const GET_CHILD_SUB_CATEGORY_SUCCESS = "GET_CHILD_SUB_CATEGORY_SUCCESS";
export const GET_CHILD_SUB_CATEGORY_ERROR = "GET_CHILD_SUB_CATEGORY_ERROR";

/** POST childSubCategory API */
export const POST_CHILD_SUB_CATEGORY_PROGRESS =
  "POST_CHILD_SUB_CATEGORY_PROGRESS";
export const POST_CHILD_SUB_CATEGORY_SUCCESS =
  "POST_CHILD_SUB_CATEGORY_SUCCESS";
export const POST_CHILD_SUB_CATEGORY_ERROR = "POST_CHILD_SUB_CATEGORY_ERROR";

/** DELETE childSubCategory API */
export const DELETE_CHILD_SUB_CATEGORY_PROGRESS =
  "DELETE_CHILD_SUB_CATEGORY_PROGRESS";
export const DELETE_CHILD_SUB_CATEGORY_SUCCESS =
  "DELETE_CHILD_SUB_CATEGORY_SUCCESS";
export const DELETE_CHILD_SUB_CATEGORY_ERROR =
  "DELETE_CHILD_SUB_CATEGORY_ERROR";

/** UPDATE childSubCategory API */
export const UPDATE_CHILD_SUB_CATEGORY_PROGRESS =
  "UPDATE_CHILD_SUB_CATEGORY_PROGRESS";
export const UPDATE_CHILD_SUB_CATEGORY_SUCCESS =
  "UPDATE_CHILD_SUB_CATEGORY_SUCCESS";
export const UPDATE_CHILD_SUB_CATEGORY_ERROR =
  "UPDATE_CHILD_SUB_CATEGORY_ERROR";
