/*GET subCategory API */
export const GET_SUB_CATEGORY_PROGRESS = "GET_SUB_CATEGORY_PROGRESS";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_ERROR = "GET_SUB_CATEGORY_ERROR";

/*POST subCategory API */
export const POST_SUB_CATEGORY_PROGRESS = "POST_SUB_CATEGORY_PROGRESS";
export const POST_SUB_CATEGORY_SUCCESS = "POST_SUB_CATEGORY_SUCCESS";
export const POST_SUB_CATEGORY_ERROR = "POST_SUB_CATEGORY_ERROR";

/*DELETE subCategory API */
export const DELETE_SUB_CATEGORY_PROGRESS = "DELETE_SUB_CATEGORY_PROGRESS";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_ERROR = "DELETE_SUB_CATEGORY_ERROR";

/*UPDATE subCategory API */
export const UPDATE_SUB_CATEGORY_PROGRESS = "UPDATE_SUB_CATEGORY_PROGRESS";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_ERROR = "UPDATE_SUB_CATEGORY_ERROR";
