/** GET CATEGORY API */
export const GET_CATEGORY_PROGRESS = "GET_CATEGORY_PROGRESS";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

/** POST CATEGORY API */
export const POST_CATEGORY_PROGRESS = "POST_CATEGORY_PROGRESS";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_ERROR = "POST_CATEGORY_ERROR";
export const POST_CATEGORY_DUPLICATE = "POST_CATEGORY_DUPLICATE";

/** DELETE CATEGORY API */
export const DELETE_CATEGORY_PROGRESS = "DELETE_CATEGORY_PROGRESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

/** UPDATE CATEGORY API */
export const UPDATE_CATEGORY_PROGRESS = "UPDATE_CATEGORY_PROGRESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

/*GET subCategory API */
export const GET_SUB_CATEGORY_PROGRESS = "GET_SUB_CATEGORY_PROGRESS";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_ERROR = "GET_SUB_CATEGORY_ERROR";

/*POST subCategory API */
export const POST_SUB_CATEGORY_PROGRESS = "POST_SUB_CATEGORY_PROGRESS";
export const POST_SUB_CATEGORY_SUCCESS = "POST_SUB_CATEGORY_SUCCESS";
export const POST_SUB_CATEGORY_ERROR = "POST_SUB_CATEGORY_ERROR";
export const POST_SUB_CATEGORY_DUPLICATE = "POST_SUB_CATEGORY_DUPLICATE";

/*DELETE subCategory API */
export const DELETE_SUB_CATEGORY_PROGRESS = "DELETE_SUB_CATEGORY_PROGRESS";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_ERROR = "DELETE_SUB_CATEGORY_ERROR";

/*UPDATE ChildSubCategory API */
export const UPDATE_CHILD_SUB_CATEGORY_PROGRESS = "UPDATE_CHILD_SUB_CATEGORY_PROGRESS";
export const UPDATE_CHILD_SUB_CATEGORY_SUCCESS = "UPDATE_CHILD_SUB_CATEGORY_SUCCESS";
export const UPDATE_CHILD_SUB_CATEGORY_ERROR = "UPDATE_CHILD_SUB_CATEGORY_ERROR";
export const UPDATE_CHILD_SUB_CATEGORY_DUPLICATE = "UPDATE_CHILD_SUB_CATEGORY_DUPLICATE";

/*GET ChildSubCategory API */
export const GET_CHILD_SUB_CATEGORY_PROGRESS = "GET_CHILD_SUB_CATEGORY_PROGRESS";
export const GET_CHILD_SUB_CATEGORY_SUCCESS = "GET_CHILD_SUB_CATEGORY_SUCCESS";
export const GET_CHILD_SUB_CATEGORY_ERROR = "GET_CHILD_SUB_CATEGORY_ERROR";

/*POST ChildSubCategory API */
export const POST_CHILD_SUB_CATEGORY_PROGRESS = "POST_CHILD_SUB_CATEGORY_PROGRESS";
export const POST_CHILD_SUB_CATEGORY_SUCCESS = "POST_CHILD_SUB_CATEGORY_SUCCESS";
export const POST_CHILD_SUB_CATEGORY_ERROR = "POST_CHILD_SUB_CATEGORY_ERROR";
export const POST_CHILD_SUB_CATEGORY_DUPLICATE = "POST_CHILD_SUB_CATEGORY_DUPLICATE";

/*DELETE ChildSubCategory API */
export const DELETE_CHILD_SUB_CATEGORY_PROGRESS = "DELETE_CHILD_SUB_CATEGORY_PROGRESS";
export const DELETE_CHILD_SUB_CATEGORY_SUCCESS = "DELETE_CHILD_SUB_CATEGORY_SUCCESS";
export const DELETE_CHILD_SUB_CATEGORY_ERROR = "DELETE_CHILD_SUB_CATEGORY_ERROR";

/*UPDATE ChildSubCategory API */
export const UPDATE_SUB_CATEGORY_PROGRESS = "UPDATE_SUB_CATEGORY_PROGRESS";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_ERROR = "UPDATE_SUB_CATEGORY_ERROR";
export const UPDATE_SUB_CATEGORY_DUPLICATE = "UPDATE_SUB_CATEGORY_DUPLICATE";
